import { Inter } from 'next/font/google'
import '@/app/globals.css'
import Link from 'next/link'
import Logo from '@/app/assets/logo.png'
import Image from 'next/image'
import UserBox from '@/components/UserBoxSkeleton'
import Sidebar from '@/components/Dashboard/Sidebar'
import Header from '@/components/Dashboard/Header'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const menuData = [
  {
      name: 'Dashboard',
      href: '/dashboard',
  },
  {
      name: 'Post',
      child: [
          {
              name: 'Your Posts',
              href: '/category/tech/news',
          },
          {
              name: 'New Posts',
              href: '/category/tech/sale',
          },
          {
              name: 'All Posts',
              href: '/category/tech/sale',
          }
      ]
  },
  {
      name: 'User',
      child: [
          {
              name: 'All Users',
              href: '/category/tech/news',
          },
          {
              name: 'Profile',
              href: '/category/tech/sale',
          },
      ]
  },
  {
      name: 'About Us',
      href: '/about-us',
  }
]


export default function Layout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <div>
        <Sidebar menuData={menuData}/>
        <div>
          <Header />
          {children}
        </div>
      </div>
    </body>
    </html>

  )
}
